apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  deployment: kuadrant-helm-deploy

resources:
  - ../tasks/deploy/
  - ../tasks/login/
  - pipeline.yaml
  - pipeline-nightly-update.yaml
  - eventlistener.yaml
  - trigger-nightly-update.yaml
