apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kuadrant-nightly-update-pipeline
spec:
  params:
  - description: API URL of the Openshift cluster
    name: kube-api
    type: string
  - description: Istio deployment. Only these values 'sail', 'ossm', 'ossm3'
    name: istio-provider
    type: string
    default: ossm3
  tasks:
  - name: clone
    taskRef:
      kind: Task
      name: clone
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: kubectl-login
    params:
    - name: kube-api
      value: $(params.kube-api)
    - name: testsuite-image
      value: quay.io/rhn_support_azgabur/alpine/k8s:latest
    taskRef:
      kind: Task
      name: kubectl-login
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: nightly-image-date
    taskRef:
      kind: Task
      name: nightly-image-date
  - name: helm-uninstall
    params:
      - name: kubeconfig-path
        value: $(tasks.kubectl-login.results.kubeconfig-path)
    runAfter:
    - clone
    - kubectl-login
    taskRef:
      kind: Task
      name: helm-uninstall
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: helm-install-nightly
    params:
      - name: index-image
        value: $(tasks.nightly-image-date.results.nightly-image)
      - name: channel
        value: preview
      - name: istio-provider
        value: $(params.istio-provider)
      - name: kubeconfig-path
        value: $(tasks.kubectl-login.results.kubeconfig-path)
    runAfter:
    - helm-uninstall
    - nightly-image-date
    taskRef:
      kind: Task
      name: helm-install
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
